# Generated by Django 6.0.7 on 2026-07-23 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('num_hilos', models.PositiveIntegerField(default=0, editable=False)),
                ('num_posts', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['slug'], name='forum_categ_slug_ba07a1_idx'), models.Index(fields=['id_original'], name='forum_categ_id_orig_812cc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(blank=True, null=True, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('autor_historico', models.CharField(blank=True, max_length=100)),
                ('url_original', models.URLField(blank=True)),
                ('archivo_html', models.CharField(blank=True, max_length=255)),
                ('es_historico', models.BooleanField(default=True)),
                ('sticky', models.BooleanField(default=False)),
                ('cerrado', models.BooleanField(default=False)),
                ('num_posts', models.PositiveIntegerField(default=0, editable=False)),
                ('num_vistas', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField()),
                ('ultimo_post', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilos', to='forum.categoria')),
            ],
            options={
                'verbose_name': 'hilo',
                'verbose_name_plural': 'hilos',
                'ordering': ['-sticky', '-ultimo_post'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(blank=True, null=True, unique=True)),
                ('autor_historico', models.CharField(blank=True, max_length=100)),
                ('msg_id', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('contenido', models.TextField()),
                ('contenido_html', models.TextField(blank=True)),
                ('creado', models.DateTimeField()),
                ('editado', models.DateTimeField(blank=True, null=True)),
                ('es_historico', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.hilo')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField()),
                ('url_r2', models.URLField(blank=True)),
                ('archivo_local', models.CharField(blank=True, max_length=255)),
                ('descargada', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='forum.post')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
            },
        ),
        migrations.AddIndex(
            model_name='hilo',
            index=models.Index(fields=['categoria', '-ultimo_post'], name='forum_hilo_categor_972527_idx'),
        ),
        migrations.AddIndex(
            model_name='hilo',
            index=models.Index(fields=['slug'], name='forum_hilo_slug_555d56_idx'),
        ),
        migrations.AddIndex(
            model_name='hilo',
            index=models.Index(fields=['id_original'], name='forum_hilo_id_orig_0944f4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['hilo', 'orden'], name='forum_post_hilo_id_ccfadd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['autor'], name='forum_post_autor_i_eaf204_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id_original'], name='forum_post_id_orig_eb74c0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagen',
            index=models.Index(fields=['post'], name='forum_image_post_id_c97112_idx'),
        ),
        migrations.AddIndex(
            model_name='imagen',
            index=models.Index(fields=['descargada'], name='forum_image_descarg_a5f79c_idx'),
        ),
    ]
