# Generated by Django 6.0.7 on 2026-07-23 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('moderador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertencias_emitidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'advertencia',
                'verbose_name_plural': 'advertencias',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('tipo', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente')], default='temporal', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField(blank=True, null=True)),
                ('levantado', models.DateTimeField(blank=True, null=True)),
                ('levantado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baneos_levantados', to=settings.AUTH_USER_MODEL)),
                ('moderador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baneos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baneos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'baneo',
                'verbose_name_plural': 'baneos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['usuario', 'activo'], name='forum_ban_usuario_41c386_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('editar_post', 'Editar post'), ('borrar_post', 'Borrar post'), ('cerrar_hilo', 'Cerrar hilo'), ('abrir_hilo', 'Abrir hilo'), ('mover_hilo', 'Mover hilo'), ('editar_usuario', 'Editar usuario'), ('banear', 'Bannear usuario'), ('levantar_ban', 'Levantar baneo'), ('advertir', 'Advertir usuario'), ('resolver_reporte', 'Resolver reporte')], max_length=30)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('moderador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_moderacion', to=settings.AUTH_USER_MODEL)),
                ('target_hilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.hilo')),
                ('target_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.post')),
                ('target_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderado_en', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de moderación',
                'verbose_name_plural': 'logs de moderación',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['creado'], name='forum_moder_creado_2e2770_idx'), models.Index(fields=['moderador'], name='forum_moder_moderad_123ef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spam', 'Spam'), ('acoso', 'Acoso'), ('contenido_inapropiado', 'Contenido inapropiado'), ('discurso_odio', 'Discurso de odio'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('nota_moderacion', models.TextField(blank=True)),
                ('hilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='forum.hilo')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='forum.post')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_hechos', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado'], name='forum_repor_estado_b99023_idx'), models.Index(fields=['creado'], name='forum_repor_creado_9c29d2_idx')],
            },
        ),
    ]
