# Generated by Django 6.0.7 on 2026-07-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_warning_ban_moderationlog_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilo',
            name='contenido_apertura',
            field=models.TextField(blank=True),
        ),
    ]
