# Generated by Django 6.0.7 on 2026-07-25 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_hilo_contenido_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_clashbang',
            field=models.BooleanField(default=False, help_text='True = Foro ClashBang (nuevo), False = Archivo Histórico'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_titulo', models.CharField(default='Hijo de Fr4n', max_length=50)),
                ('puntos_barra', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado_usuario', models.CharField(choices=[('activo', 'Activo'), ('baneado', 'Game Over'), ('desaparecido', 'Desaparecido')], default='activo', max_length=20)),
                ('color_rango', models.CharField(default='#94a3b8', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
