# Generated by Django 6.0.7 on 2026-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_categoria_es_clashbang_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)'),
        ),
    ]
