# Generated by Django 6.0.7 on 2026-07-27 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_categoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
