# Generated by Django 6.0.7 on 2026-07-27 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_hilo_creado_alter_post_creado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('hilo', 'orden'), name='post_orden_unico_por_hilo'),
        ),
    ]
